# ServerPi Services - Wordpress Compose File
# Prepared by Samyar Sadat Akhavi, 2024-2026. 

services:
    database:
        image: mysql:26.7
        container_name: wordpress-test-db
        hostname: wordpress-test-db
        restart: unless-stopped
        env_file:
            - .env
            - database.secrets.env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - internal-net

    wordpress:
        image: wordpress:7.1-fpm-alpine
        container_name: wordpress-test
        hostname: wordpress-test
        restart: unless-stopped
        depends_on:
            - database
        env_file:
            - .env
            - wordpress.secrets.env
        volumes:
            - wordpress:/var/www/html
            - ./wp_php_conf.ini:/usr/local/etc/php/conf.d/php-config.ini:ro
        networks:
            - internal-net

    nginx:
        image: nginx:1.27-alpine
        container_name: wordpress-test-nginx
        hostname: wordpress-test-nginx
        restart: unless-stopped
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html:ro
            - ./nginx-conf:/etc/nginx/conf.d:ro
        networks:
            - default
            - internal-net

networks:
    internal-net:
    default:
        name: $DOCKER_MY_NETWORK
        external: true

volumes:
    db_data:
    wordpress: