# ServerPi Services - Caddy V2 Compose File
# Prepared by Samyar Sadat Akhavi, 2024. 

services:
    caddy:
        image: caddy:latest
        container_name: caddy
        hostname: caddy
        restart: unless-stopped
        env_file: .env
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
            - "2019:2019"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_config:/config
            - ./caddy_data:/data

    # LOG AGENT FOR PUSHING LOGS TO LOKI
    promtail:
        image: grafana/promtail:latest
        container_name: caddy-promtail
        hostname: caddy-promtail
        restart: unless-stopped
        depends_on:
            - caddy
        volumes:
            - ./promtail-config.yml:/etc/promtail-config.yml
            - ./caddy_data/logs:/var/log/caddy:ro
        command:
            - '-config.file=/etc/promtail-config.yml'

networks:
    default:
        name: $DOCKER_MY_NETWORK
        external: true