# ServerPi Services - Caddy V2 Compose File
# Prepared by Samyar Sadat Akhavi, 2024-2026. 

services:
    caddy:
        image: caddy:2.11.4
        container_name: caddy
        hostname: caddy
        restart: unless-stopped
        env_file: .env
        ports:
            - 80:80
            - 9180:9180
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_config:/config
            - caddy_data:/data
        networks:
            default:
                ipv4_address: 172.30.0.100

    # LOG AGENT FOR PUSHING LOGS TO LOKI
    alloy:
        image: grafana/alloy:v1.18.1
        container_name: caddy-alloy
        hostname: caddy-alloy
        restart: unless-stopped
        depends_on:
            - caddy
        env_file:
            - .env
            - secrets.env
        volumes:
            - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
            - caddy_data/logs:/var/log/caddy:ro
            - alloy_data:/var/lib/alloy/data
        command:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - --disable-reporting
            - /etc/alloy/config.alloy

networks:
    default:
        name: $DOCKER_MY_NETWORK
        external: true

volumes:
    caddy_config:
    caddy_data:
    alloy_data: