clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: caddy_access_log
      static_configs:
          - targets:
                - localhost
            labels:
                job: caddy_access_log
                host: ssa-selfhosted.com
                agent: caddy-promtail
                __path__: /var/log/caddy/*.log

      pipeline_stages:
          - json:
                expressions:
                    request_remote_ip: request.remote_ip
                    request_client_ip: request.client_ip
          - geoip:
                db: "/etc/GeoLite2-City.mmdb"
                source: "request_remote_ip"
                db_type: "city"
          - geoip:
                db: "etc/GeoLite2-ASN.mmdb"
                source: "request_remote_ip"
                db_type: "asn"