# ServerPi Services - Mail Client Compose File
# Prepared by Samyar Sadat Akhavi, 2026. 

services:
    # WEBMAIL CLIENT
    roundcube:
        image: roundcube/roundcubemail:1.7.3-apache
        container_name: roundcube
        hostname: roundcube
        restart: unless-stopped
        env_file:
            - .env
            - secrets.env
        extra_hosts:
            - "${MAIL_HOST}:${HOST_IP_ADDR}"
        volumes:
            - data_db:/var/roundcube/db
            - data_config:/var/www/html/config
            - data_tmp:/tmp/roundcube-temp
            - ./roundcube_conf.inc.php:/var/www/html/config/custom.inc.php:ro

networks:
    default:
        name: $DOCKER_MY_NETWORK
        external: true

volumes:
    data_db:
    data_config:
    data_tmp: