---
- name: Secure declared secret paths
  become: true
  block:
    - name: Secure secret environment variable files
      ansible.builtin.file:
          path: "{{serverpi_services_root}}/{{item}}"
          state: file
          owner: root
          group: docker
          mode: "0640"
      loop: "{{serverpi_secret_config.get('env_files', {}).keys() | list}}"
      loop_control:
          label: "{{item}}"
      register: serverpi_secret_env_file_permissions

    - name: Secure raw secret files
      ansible.builtin.file:
          path: "{{serverpi_services_root}}/{{item}}"
          state: file
          owner: root
          group: root
          mode: "0600"
      loop: "{{serverpi_secret_config.get('raw_files', {}).keys() | list}}"
      loop_control:
          label: "{{item}}"
      register: serverpi_raw_secret_file_permissions

    - name: Secure configured service directories
      ansible.builtin.file:
          path: "{{serverpi_services_root}}/{{item}}"
          state: directory
          owner: root
          group: root
          mode: u=rwX,go=
          recurse: true
      loop: "{{serverpi_secret_config.get('secure_directories', [])}}"
      loop_control:
          label: "{{item}}"
      register: serverpi_secure_directory_permissions
