# THIS IS A COPY OF THE AUTHELIA CONFIGURATION FILE AT ./config/configuration.yml
# Modify this file according to your needs and copy it to that location.

# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
# Set also AUTHELIA_JWT_SECRET_FILE
theme: auto

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
    file:
        path: /config/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
    issuer: ssa-selfhosted.com

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
    default_policy: two_factor

# Session https://www.authelia.com/configuration/session/introduction/
# Set also AUTHELIA_SESSION_SECRET_FILE
session:
    name: authelia_session
    same_site: lax
    inactivity: 5m
    expiration: 1h
    remember_me: 1M
    cookies:
        - domain: ssa-selfhosted.com
          authelia_url: https://auth.ssa-selfhosted.com
          default_redirection_url: https://auth.ssa-selfhosted.com/
          name: authelia_session
          same_site: lax
          inactivity: 5m
          expiration: 1h
          remember_me: 1d

    # https://www.authelia.com/configuration/session/redis/
    # Set also AUTHELIA_SESSION_REDIS_PASSWORD_FILE if appropriate
    redis:
        host: redis
        port: 6379

# Storage https://www.authelia.com/configuration/storage/postgres/
# Set also AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
# Set also AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
storage:
    postgres:
        host: database
        database: authelia
        username: authelia

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
# Set also AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
notifier:
    smtp:
        host: in-v3.mailjet.com
        port: 587
        username: [MAILJET_API_USERNAME]
        sender: "Authelia <authelia@ssa-selfhosted.com>"