---
- name: Reload systemd
  ansible.builtin.systemd_service:
      daemon_reload: true

- name: Reload UFW
  community.general.ufw:
      state: reloaded

- name: Restart DNS resolver
  ansible.builtin.systemd_service:
      name: systemd-resolved
      state: restarted

- name: Apply Netplan configuration
  ansible.builtin.command: /usr/sbin/netplan apply

- name: Restart Docker
  ansible.builtin.systemd_service:
      name: docker
      state: restarted
