# ServerPi Services - Monitoring Services Compose File
# Prepared by Samyar Sadat Akhavi, 2024. 

services:
    # MONITORING SYSTEM AND THE METRICS DATABASE
    prometheus:
        image: prom/prometheus:v2.42.0
        container_name: prometheus
        hostname: prometheus
        user: root
        restart: unless-stopped
        depends_on:
            - cadvisor
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=240h'
            - '--web.enable-lifecycle'
        volumes:
            - ./prometheus_data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        expose:
            - "9090"
        labels:
            org.label-schema.group: "monitoring"

    # WEB BASED UI VISUALISATION OF METRICS
    grafana:
        image: grafana/grafana:9.4.3
        container_name: grafana
        hostname: grafana
        user: root
        restart: unless-stopped
        env_file:
            - .env
            - secrets.env
        volumes:
            - ./grafana_data:/var/lib/grafana
        expose:
            - "3000"
        labels:
            org.label-schema.group: "monitoring"

    # HOST LINUX MACHINE METRICS EXPORTER
    node-exporter:
        image: prom/node-exporter:v1.5.0
        container_name: node-exporter
        hostname: node-exporter
        restart: unless-stopped
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        expose:
            - "9100"
        labels:
            org.label-schema.group: "monitoring"

    # DOCKER CONTAINERS METRICS EXPORTER
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.1
        container_name: cadvisor
        hostname: cadvisor
        restart: unless-stopped
        privileged: true
        devices:
            - /dev/kmsg:/dev/kmsg
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /cgroup:/cgroup:ro
        expose:
            - "3000"
        labels:
            org.label-schema.group: "monitoring"

    # LOG MANAGEMENT WITH LOKI
    loki:
        image: grafana/loki:main-0295fd4
        container_name: loki
        hostname: loki
        user: root
        restart: unless-stopped
        volumes:
            - ./loki_data:/loki
            - ./loki-config.yml:/etc/loki-config.yml
        command:
            - '-config.file=/etc/loki-config.yml'
        ports:
            - "3100:3100"
        labels:
            org.label-schema.group: "monitoring"

networks:
    default:
        name: $DOCKER_MY_NETWORK
        external: true