# ServerPi Services - Loki Config File
# Prepared by Samyar Sadat Akhavi, 2024. 

auth_enabled: false

server:
    http_listen_port: 3100

common:
    path_prefix: /loki
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

storage_config:
    tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h

    filesystem:
        directory: /loki/chunks

schema_config:
    configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: index_
              period: 24h

query_range:
    parallelise_shardable_queries: false

compactor:
    working_directory: /loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

limits_config:
    retention_period: 240h
    split_queries_by_interval: 0

ruler:
    alertmanager_url: http://alertmanager:9093

analytics:
    reporting_enabled: false