# ServerPi Services - Prometheus Config File
# Prepared by Samyar Sadat Akhavi, 2024. 

global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "nodeexporter"
      static_configs:
          - targets: ["node-exporter:9100"]
    - job_name: "cadvisor"
      static_configs:
          - targets: ["cadvisor:8080"]
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
    - job_name: "caddy"
      static_configs:
          - targets: ["caddy:2019"]
    - job_name: "docker-registry"
      static_configs:
          - targets: ["docker-registry:5001"]
    - job_name: "wireguard"
      static_configs:
          - targets: ["wireguard-server:9586"]