# ServerPi Services - Whomai Compose File
# Prepared by Samyar Sadat Akhavi, 2024. 

services:
    excalidraw:
        image: samyarsadat/service_images:excalidraw-arm64-latest
        container_name: excalidraw-web
        hostname: excalidraw-web
        restart: unless-stopped
        env_file: .env

networks:
    default:
        name: $DOCKER_MY_NETWORK
        external: true