---
serverpi_shared_secret_config:
    schema_version: 1

    generated_secrets:
        loki_basic_auth_password:
            type: random_alphanumeric
            length: 48
        loki_basic_auth_hash:
            type: bcrypt
            source: loki_basic_auth_password
            rounds: 14

    env_files: {}
    raw_files: {}
    secure_directories: []
