# ServerPi Services - WatchTower Compose File
# Prepared by Samyar Sadat Akhavi, 2024. 

services:
    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        hostname: watchtower
        restart: unless-stopped
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock