services:
    kms-server:
        image: 11notes/kms:1.0.3
        container_name: kms-server
        hostname: kms-server
        env_file: .env
        restart: unless-stopped
        ports:
            - 1688:1688/tcp
        volumes:
            - data:/kms/var
        networks:
            - internal_net

    kms-server-gui:
        image: 11notes/kms-gui:1.0.3
        container_name: kms-server-gui
        hostname: kms-server-gui
        env_file: .env
        restart: unless-stopped
        depends_on:
            kms-server:
                condition: service_healthy
                restart: true
        environment:
            - PORT=3688
        ports:
            - 3688:3688/tcp
        volumes:
            - data:/kms/var
        networks:
            - internal_net

volumes:
    data:

networks:
    internal_net: